### ISSUE TITLE
Faster promisification

### ISSUE THREAD

**Issue by benjamingr** [sonnyp/polygoat#3]
Hey, you should consider a faster way to promisify functions when in Node. The current approach requires a closure each time and it's pretty slow'ish.

Alternatively, you can provide a hook so that people can provide their own promisification if they're using promise libraries like bluebird that already do this fast.

**Comment by sonnyp** [comment]
> you should consider a faster way to promisify functions when in Node. 

What do you recommend?

> The current approach requires a closure each time and it's pretty slow'ish.

Based on what? 

> Alternatively, you can provide a hook so that people can provide their own promisification if they're using promise libraries like bluebird that already do this fast. 

I don't see the benefit ?

**Comment by sonnyp** [comment]
added a benchmark https://github.com/sonnyp/polygoat/pull/4

Looks plenty fast, I don't think it can get any faster, but if you have a tip please let me know.

IMHO If you _really_ need to run your code hundreds of thousands of time per seconds you probably shouldn't use promise anyway, nor callback for that matter and use a queue (assuming async code), in fact if you need to run IO operations at that speed on a single Node.js instance there's probably something wrong with your infrastructure.

**Comment by benjamingr** [comment]
It's slow and the benchmark is bonkers, sorry. You can check @spion'd benchmarks at the bluebird repo or at his repo about it - and check promisify.js at bluebird for an implementation idea.

**Comment by sonnyp** [comment]
> It's slow

again; based on what? relative to what? for what use case?

> the benchmark is bonkers, sorry

Maybe, I don't have much experience there but still I doubt "promisifying" will ever be anyone's bottleneck. Anyway if you could explain how/why the benchmark is bonkers that would be very helpful.

> You can check @spion'd benchmarks at the bluebird repo or at his repo about it

I had a quick look, I'm sure it's a very fine benchmark and is probably much better than my naive benchmark but it's quite complex and I don't want to spend my time on something I simply see no benefit for (see https://github.com/sonnyp/polygoat/issues/3#issuecomment-210314778).

> and check promisify.js at bluebird for an implementation idea.

Okay I did, the code is interesting, it uses eval / code generation by default and fallbacks to a closure. 

Thanks for the suggestion but again, at that scale, I really don't care if bluebird _could_ "promisify" a few hundreds more functions per seconds than polygoat. Plus I don't want polygoat to grows into a hundreds of locs library (mostly for load time in browsers), that's why it doesn't require/include Promise polyfill

**Comment by benjamingr** [comment]
> again; based on what? relative to what? for what use case?

Relative to how bluebird and other libraries promisify. Based on running closure based promisification vs dynamic compilation based promisification. For the use case of every library call ever - sure it's not a bottleneck usually but it's incurred on every library function call - if you call the library hundreds of thousands of times (think `fs`) in the server it amounts to a noticeable amount. 

The more expensive an abstraction is the more likely a user will look for shortcuts around it so it is our duty as library makers to make an effort to avoid performance penalties when easy.

> Thanks for the suggestion but again, at that scale, I really don't care if bluebird could "promisify" a few hundreds more functions per seconds than polygoat. Plus I don't want polygoat to grows into a hundreds of locs library (mostly for load time in browsers), that's why it doesn't require/include Promise polyfill

Fair enough, sacrificing performance for file size is a reasonable thing to do IMO.

**Comment by sonnyp** [comment]
On a different subject, do you have thoughts on https://github.com/sonnyp/polygoat/pull/2 (ignore the github conversation, checkout the reddit conversation for background) ?

**Comment by sonnyp** [comment]
@benjamingr the benchmark was indeed pretty broken, I fixed it in https://github.com/sonnyp/polygoat/commit/819871170d854738b6715f28d47b409a68c1cb99

bluebird call time is now faster than polygoat on Node.js but polygoat remains faster in browsers
https://github.com/sonnyp/polygoat/tree/master/benchmark

Still plenty fast but I might work on the eval trick and load it on Node.js only so that the file size doesn't increase, Could be fun.
